### ISSUE TITLE
net.minecraft.ReportedException: Ticking player

### ISSUE THREAD

**Issue by DaftHunk** [DaftHunk/Heroes-of-Mine-and-Crafting-Forge#16]
```[15May2024 21:58:37.046] [Server thread/WARN] [net.minecraft.server.network.ServerConnectionListener/]: Failed to handle packet for /90.105.223.67:54596
net.minecraft.ReportedException: Ticking player
at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:530) ~[server-1.20.1-20230612.114412-srg.jar%23705!/:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:262) ~[server-1.20.1-20230612.114412-srg.jar%23705!/:?]
at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[server-1.20.1-20230612.114412-srg.jar%23705!/:?]
at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.20.1-20230612.114412-srg.jar%23705!/:?]
at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[server-1.20.1-20230612.114412-srg.jar%23705!/:?]
at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23705!/:?]
at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23705!/:?]
at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23705!/:?]
at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23705!/:?]
at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.world.item.Item.relics$processTooltip(net.minecraft.world.item.ItemStack, net.minecraft.world.level.Level, java.util.List)'
at net.minecraft.world.item.Item.handler$djk000$relics$appendHoverText(Item.java:3555) ~[server-1.20.1-20230612.114412-srg.jar%23705!/:?]
at net.minecraft.world.item.Item.m_7373_(Item.java) ~[server-1.20.1-20230612.114412-srg.jar%23705!/:?]
at ludichat.cobbreeding.PokemonEgg.m_7373_(PokemonEgg.java:99) ~[Cobbreeding-forge-1.6.0.jar%23456!/:?]
at net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:631) ~[server-1.20.1-20230612.114412-srg.jar%23705!/:?]
at ludichat.cobbreeding.PokemonEgg.m_6883_(PokemonEgg.java:118) ~[Cobbreeding-forge-1.6.0.jar%23456!/:?]
at net.minecraft.world.item.ItemStack.m_41666_(ItemStack.java:481) ~[server-1.20.1-20230612.114412-srg.jar%23705!/:?]
at net.minecraftforge.common.extensions.IForgeItem.onInventoryTick(IForgeItem.java:353) ~[forge-1.20.1-47.2.20-universal.jar%23710!/:?]
at net.minecraftforge.common.extensions.IForgeItemStack.onInventoryTick(IForgeItemStack.java:306) ~[forge-1.20.1-47.2.20-universal.jar%23710!/:?]
at net.minecraft.world.entity.player.Inventory.m_36068_(Inventory.java:230) ~[server-1.20.1-20230612.114412-srg.jar%23705!/:?]
at net.minecraft.world.entity.player.Player.m_8107_(Player.java:499) ~[server-1.20.1-20230612.114412-srg.jar%23705!/:?]
at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2298) ~[server-1.20.1-20230612.114412-srg.jar%23705!/:?]
at net.minecraft.world.entity.player.Player.m_8119_(Player.java:241) ~[server-1.20.1-20230612.114412-srg.jar%23705!/:?]
at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467) ~[server-1.20.1-20230612.114412-srg.jar%23705!/:?]
... 9 more```

**Comment by DaftHunk** [comment]
Sera corrigé à la prochain màj : https://modrinth.com/mod/cobbreeding/version/trs4cjVB
